spring:
  redis:
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # 连接池最大连接数（使用负值表示没有限制）
    max-active: 200
    timeout: 1000
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    jedis:
      pool:
        max-wait: -1
        max-idle: 10
        min-idle: 0
  #覆盖同名的bean
  main:
    allow-bean-definition-overriding: true