spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/weixin_bate?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    druid:
      initial-size: 5
      # 最大连接池数量
      max-active: 100
      # 最小连接池数量
      min-idle: 10
      # 配置获取连接等待超时的时间
      max-wait: 60000
  redis:
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # 连接池最大连接数（使用负值表示没有限制）
    max-active: 200
    timeout: 1000
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    jedis:
      pool:
        max-wait: -1
        max-idle: 10
        min-idle: 0
    #覆盖同名的bean
    main:
      allow-bean-definition-overriding: true
mybatis:
  type-aliases-package: com.weixin.entry
  mapper-locations: classpath:/mapper.**.xml